colour=input("enter a colour:")
plural_noun=input("Enter a plural noun")
celebrity=input("Enter a celebrity")
print("roses are" + colour)
print(plural_noun + "are blue")
print(" I love" + celebrity)